[package]
name = "gw2-arcdps-utils"
version = "0.1.0"
edition = "2021"
authors = ["Zerthox <zerthox@gmail.com>"]
repository = "https://github.com/zerthox/gw2-arcdps-utils"

[dependencies]
arcdps = { git = "https://github.com/greaka/arcdps_bindings", branch = "master" }
num_enum = "0.5"
serde_crate = { package = "serde", version = "1.0", features = ["derive"], optional = true }
strum = "0.23"
strum_macros = "0.23"
windows = { version = "0.28", features = ["System", "Win32_Media"] }

[features]
default = []
serde = ["serde_crate"]
