[package]
name = "arc_util"
version = "0.5.0"
edition = "2021"
authors = ["Zerthox <zerthox@gmail.com>"]
repository = "https://github.com/zerthox/arcdps-utils"

[dependencies]
arcdps = "0.7"
chrono = { version = "0.4", optional = true }
num_enum = "0.5"
serde_crate = { package = "serde", version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
strum = "0.24"
strum_macros = "0.24"
windows = { version = "0.33", features = ["Win32_Media"] }

[features]
default = []
serde = ["serde_crate"]
settings = ["serde_crate", "serde_json"]
log = ["chrono"]
