[package]
name = "arc_util"
version = "0.5.2"
edition = "2021"
authors = ["Zerthox <zerthox@gmail.com>"]
repository = "https://github.com/zerthox/arcdps-utils"

[dependencies]
arcdps = "0.7"
chrono = { version = "0.4", optional = true }
num_enum = "0.5"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
strum = "0.24"
strum_macros = "0.24"

[dependencies.windows]
version = "0.34"
features = [
    "System",
    "Win32_Foundation",
    "Win32_Media",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging"
]

[features]
default = []
settings = ["serde", "serde_json"]
log = ["chrono"]
