[package]
name = "arc_util"
version = "0.4.2"
edition = "2021"
authors = ["Zerthox <zerthox@gmail.com>"]
repository = "https://github.com/zerthox/gw2-arcdps-utils"

[dependencies]
arcdps = { git = "https://github.com/greaka/arcdps_bindings", branch = "master" }
chrono = { version = "0.4", optional = true }
num_enum = "0.5"
serde_crate = { package = "serde", version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
strum = "0.23"
strum_macros = "0.23"
windows = { version = "0.32", features = ["Win32_Media"] }

[features]
default = []
serde = ["serde_crate"]
settings = ["serde_crate", "serde_json"]
log = ["chrono"]
